name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  on-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: test-run
      run: dist/cpc version
    
    - name: make test
      run: make test

  on-windows-with-msvc:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up MSVC 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2022

    - name: make
      run: make

    - name: test-run
      run: dist/cpc version
    
    - name: make test
      run: make test

  on-windows-with-mingw:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: set up mingw
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: |
          base-devel
      
    - name: make
      run: make CC=gcc

    - name: test-run
      run: dist/cpc version
    
    - name: make test
      run: make test CC=gcc